[package]
name = "trustme"
version = "0.1.0"
edition = "2021"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = 'abort'
strip = true
debug = false

[dependencies]
axum = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.47", features = ["full"] }
tower-http = { version = "0.6", features = ["cors", "trace"] }
tower = { version = "0.5", features = ["limit", "buffer", "timeout"] }
bb8 = "0.9"
bb8-redis = "0.24"
redis = { version = "0.32", features = ["tokio-comp", "tokio-native-tls-comp"] }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
num_cpus = "1.17"
tracing = "0.1"
sentry = { version = "0.41", features = ["tracing"] }
sentry-tower = "0.41"
uuid = { version = "1.17", features = ["serde", "v4"] }
chrono = { version = "0.4", features = ["serde"] }
moka = { version = "0.12", features = ["future"] }
reqwest = { version = "0.12", features = ["gzip"] }
scraper = "0.23"
thiserror = "2.0"
regex = "1.11"
lazy_static = "1.5"
url = "2.5"
once_cell = "1.21"
log = "0.4.27"

[target.'cfg(windows)'.dependencies]
windows = { version = "0.61", features = [
    "Win32_System_Console",
    "Win32_System_SystemServices",
    "Win32_Globalization"
] }

[dev-dependencies]
tokio = { version = "1.46", features = ["macros", "rt-multi-thread"] }
