[package]
name = "trustme"
version = "0.1.0"
edition = "2021"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = 'abort'
strip = true
debug = false

[dependencies]
axum = "0.8"
axum-messages = "0.8"
axum-extra = { version = "0.10", features = ["cookie"] }
argon2 = "0.5"
askama = "0.14"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.47", features = ["full"] }
tower-http = { version = "0.6", features = ["fs", "cors", "trace", "compression-br", "compression-deflate", "compression-gzip", "compression-zstd"] }
tower-sessions = { version = "0.14", features = ["axum-core", "tower-sessions-memory-store"] }
tower-sessions-moka-store = "0.15"
tower-sessions-sqlx-store = { version = "0.15", features = ["postgres"] }
tower = { version = "0.5", features = ["limit", "buffer", "timeout"] }
bb8 = "0.9"
bb8-redis = "0.24"
redis = { version = "0.32", features = ["tokio-comp", "tokio-native-tls-comp"] }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
num_cpus = "1.17"
tracing = "0.1"
sentry = { version = "0.42", features = ["tracing"] }
sentry-tower = "0.42"
uuid = { version = "1.17", features = ["serde", "v4"] }
chrono = { version = "0.4", features = ["serde"] }
chrono-tz = "0.10"
moka = { version = "0.12", features = ["future"] }
reqwest = { version = "0.12", features = ["gzip"] }
scraper = "0.23"
thiserror = "2.0"
regex = "1.11"
lazy_static = "1.5"
url = "2.5"
once_cell = "1.21"
log = "0.4.27"
sea-orm = { version = "1.1", features = ["sqlx-postgres", "runtime-tokio-rustls", "macros"] }
jsonwebtoken = "9.3"
time = "0.3.37"

[dev-dependencies]
tokio = { version = "1.46", features = ["macros", "rt-multi-thread"] }
