[package]
name = "entities"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
name = "entities"
path = "src/lib.rs"

[dependencies]
serde = { version = "1", features = ["derive"] }
uuid = { version = "1.17", features = ["serde", "v4"] }

[dependencies.sea-orm]
version = "1.1"
