name: Build and Push Docker Image

env:
  CARGO_TERM_COLOR: always
  DOCKER_IMAGE: koval01/tma-rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write
  packages: write
  issues: write
  pull-requests: write

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y pkg-config libssl-dev build-essential

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-unknown-linux-gnu
          override: true

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          prefix-key: x86_64-unknown-linux-gnu

      - name: Build Release Binary
        run: cargo build --release

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: "tma-rust"
          path: target/release/tma-rust

      - name: Get short SHA and current date
        id: vars
        shell: bash
        run: |
          if [[ matrix.os == "windows-latest" ]]; then
            echo "short_sha=${GITHUB_SHA::8}" >> $env:GITHUB_OUTPUT
            echo "build_date=$(Get-Date -Format 'yyyy.MM.dd')" >> $env:GITHUB_OUTPUT
          else
            echo "short_sha=${GITHUB_SHA::8}" >> $GITHUB_OUTPUT
            echo "build_date=$(date +'%Y.%m.%d')" >> $GITHUB_OUTPUT
          fi

      - name: Prepare binaries for Docker
        run: |
          mkdir -p docker-files
          cp target/release/tma-rust docker-files/

      - name: Build Docker image for testing
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          load: true
          tags: ${{ env.DOCKER_IMAGE }}:test

      - name: Test Docker image
        env:
          REDIS_URL: ${{ secrets.REDIS_URL }}
        run: |
          docker run -d --name test-container \
            -e REDIS_URL="${REDIS_URL}" \
            -p 8000:8000 \
            ${{ env.DOCKER_IMAGE }}:test
          
          sleep 20

          docker exec test-container curl -f http://localhost:8000/healthz || exit 1
          docker stop test-container
          docker rm test-container

      - name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: koval01
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ env.DOCKER_IMAGE }}:latest

      - name: Create Release
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: softprops/action-gh-release@v2
        with:
          files: target/release/tma-rust
          name: ${{ steps.vars.outputs.build_date }}-${{ steps.vars.outputs.short_sha }}
          tag_name: ${{ steps.vars.outputs.build_date }}-${{ steps.vars.outputs.short_sha }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
